-- Oracle DDL for Helpdesk Ticket Resolution System
-- Compatible with Oracle Database 12c, 19c, 21c, 23c

-- Drop tables if they exist
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ticket_comments CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE tickets CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 1. Users table
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(120) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) DEFAULT 'USER' CHECK (role IN ('USER', 'TECHNICIAN', 'ADMIN')),
    security_question VARCHAR2(255),
    security_answer VARCHAR2(255)
);

-- 2. Tickets table (with BLOB attachment support)
CREATE TABLE tickets (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    tech_id NUMBER,
    title VARCHAR2(150) NOT NULL,
    description CLOB NOT NULL,
    priority VARCHAR2(10) DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    status VARCHAR2(20) DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
    attachment BLOB,
    attachment_name VARCHAR2(255),
    attachment_type VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tickets_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_tickets_tech FOREIGN KEY (tech_id) REFERENCES users(user_id)
);

-- 3. Ticket Discussion Comments
CREATE TABLE ticket_comments (
    comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id NUMBER NOT NULL,
    author_id NUMBER NOT NULL,
    comment_text CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comm_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(ticket_id) ON DELETE CASCADE,
    CONSTRAINT fk_comm_author FOREIGN KEY (author_id) REFERENCES users(user_id)
);

-- Seed Data: Sample Users & Technicians
INSERT INTO users (name, email, password, role) VALUES ('John Doe', 'john@example.com', 'user123', 'USER');
INSERT INTO users (name, email, password, role) VALUES ('Jane Smith', 'jane@example.com', 'user123', 'USER');
INSERT INTO users (name, email, password, role) VALUES ('Alex Tech', 'alex.tech@company.com', 'tech123', 'TECHNICIAN');
INSERT INTO users (name, email, password, role) VALUES ('Sarah Tech', 'sarah.tech@company.com', 'tech123', 'TECHNICIAN');
INSERT INTO users (name, email, password, role) VALUES ('IT Admin', 'admin@company.com', 'admin123', 'ADMIN');

COMMIT;